/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description History list. Filters compose with AND. `search` runs LIKE
         *     on the instruction field — fine for the small datasets we're
         *     working with; if it ever needs to scale, swap for FTS5.
         *
         *     Sub-tasks are NOT included as separate rows here — they live
         *     under their parent stt_pipeline job's detail page. Listing them
         *     flat would double-count cost.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Create a new job and schedule it. Returns the freshly inserted row
         *     with status=queued. The browser then opens /jobs/{id}/events to
         *     watch it run.
         */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Server-Sent Events stream. Sends:
         *       1. Persisted events with id > Last-Event-ID (replay).
         *       2. Live events arriving on the in-process bus until job is
         *          terminal AND the queue drains.
         *       3. A heartbeat every 15s so corporate proxies don't time out.
         *
         *     Client must use the browser's native EventSource — it handles
         *     reconnection automatically (sending Last-Event-ID back).
         */
        get: operations["stream_events_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Output */
        get: operations["download_output_jobs__job_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Subtasks
         * @description List all sub-tasks of an stt_pipeline parent job, ordered by `idx`.
         *     Returns [] for jobs that aren't stt_pipeline.
         */
        get: operations["list_subtasks_jobs__job_id__subtasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/subtasks/{subtask_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Subtask Output */
        get: operations["download_subtask_output_jobs_subtasks__subtask_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/subtasks/{subtask_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subtask Log */
        get: operations["get_subtask_log_jobs_subtasks__subtask_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log */
        get: operations["get_log_jobs__job_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Confirm
         * @description Submit the user's decision for whichever checkpoint the job is
         *     currently waiting on. Body shape depends on the checkpoint kind —
         *     the strategy on the agent side interprets it. Examples:
         *
         *     needs_confirm (planner task list):
         *         {"action": "confirm", "tasks": [{agent_type, label, instruction}, ...]}
         *         {"action": "cancel"}
         *
         *     needs_subject_review:
         *         {"transcript": "<corrected text>"}
         *
         *     needs_slide_confirm:
         *         {"proceed": true | false}
         *
         *     Returns the updated Job row (status will have flipped back to
         *     `running` by the time this returns, because the strategy emits its
         *     `*_resolved` event before the route response).
         */
        post: operations["submit_confirm_jobs__job_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Force-cancel a running or awaiting job. Two paths:
         *
         *       - Job sitting at a `needs_*` checkpoint → resolve the bus future
         *         with cancellation; strategy raises CheckpointCancelled which
         *         each method handles in its own sensible way (planner.confirm
         *         returns None → batch aborts; subject_review skips review;
         *         slide_confirm returns False → speech_ppt aborts).
         *       - Job RUNNING with no open checkpoint → currently a soft cancel:
         *         we mark CANCELLED in DB, the worker thread finishes whatever
         *         node it's in and the runner notices the status mismatch on
         *         commit. True interrupt-mid-node is a Phase 7 thing
         *         (it requires plumbing cancel tokens into every blocking
         *         Anthropic / Tavily call).
         */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Snapshot for the dashboard. `days` controls the rolling window
         *     for cost / count aggregations and the trend chart; recent_jobs
         *     always returns the last 5 regardless of window.
         */
        get: operations["get_summary_stats_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Audio
         * @description Accept an audio upload, persist it, return the Upload row.
         *
         *     The file is streamed to disk in chunks rather than loaded into
         *     memory — handles 100 MB files without RAM pressure.
         */
        post: operations["upload_audio_uploads_audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upload */
        get: operations["get_upload_uploads__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_audio_uploads_audio_post */
        Body_upload_audio_uploads_audio_post: {
            /**
             * File
             * @description Audio file for STT
             */
            file: string;
        };
        /** CostByTypeRow */
        CostByTypeRow: {
            /** Type */
            type: string;
            /** Cost Usd */
            cost_usd: number;
            /** Count */
            count: number;
        };
        /** DailyCostRow */
        DailyCostRow: {
            /** Date */
            date: string;
            /** Cost Usd */
            cost_usd: number;
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobCreateRequest
         * @description Submit a new job. Free-text instruction + agent type + a few knobs.
         *
         *     For single-agent jobs: pass instruction as the free-text task.
         *     For stt_pipeline jobs: pass extra={"upload_id": "<id>"} and use
         *     instruction="" (or a label) — the actual instructions come from
         *     parse_tasks after STT transcribes the audio.
         */
        JobCreateRequest: {
            /**
             * Type
             * @enum {string}
             */
            type: "company_info" | "person_info" | "translation" | "letter" | "meeting" | "verbal_cleanup" | "podcast" | "speech_ppt" | "stt_pipeline";
            /**
             * Instruction
             * @default
             */
            instruction: string;
            /**
             * Intern Name
             * @default Justin
             */
            intern_name: string;
            /**
             * Mode
             * @default short
             * @enum {string}
             */
            mode: "short" | "medium";
            /** Subdir */
            subdir?: ("daily" | "weekly" | "adhoc") | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /**
         * JobResponse
         * @description Snapshot of a job's row state. The events list is fetched
         *     separately via /jobs/{id}/events (SSE) — including it here would
         *     bloat polling responses.
         */
        JobResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "company_info" | "person_info" | "translation" | "letter" | "meeting" | "verbal_cleanup" | "podcast" | "speech_ppt" | "stt_pipeline";
            /** Instruction */
            instruction: string;
            /** Intern Name */
            intern_name: string;
            /** Mode */
            mode: string;
            /** Subdir */
            subdir: string;
            status: components["schemas"]["JobStatus"];
            /** Output Path */
            output_path?: string | null;
            /** Log Path */
            log_path?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "needs_confirm" | "needs_subject_review" | "needs_slide_confirm" | "done" | "failed" | "cancelled";
        /**
         * JobSubTaskResponse
         * @description One child of an stt_pipeline parent. Frontend renders these as
         *     nested cards under the parent job's detail page.
         */
        JobSubTaskResponse: {
            /** Id */
            id: string;
            /** Parent Id */
            parent_id: string;
            /** Idx */
            idx: number;
            /**
             * Agent Type
             * @enum {string}
             */
            agent_type: "company_info" | "person_info" | "translation" | "letter" | "meeting" | "verbal_cleanup" | "podcast" | "speech_ppt";
            /** Label */
            label: string;
            /** Instruction */
            instruction: string;
            status: components["schemas"]["JobStatus"];
            /** Output Path */
            output_path?: string | null;
            /** Log Path */
            log_path?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Error */
            error?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** JobsListResponse */
        JobsListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            /** Total */
            total: number;
        };
        /** StatsSummary */
        StatsSummary: {
            /** Window Days */
            window_days: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Job Count */
            job_count: number;
            /** Cost By Type */
            cost_by_type: components["schemas"]["CostByTypeRow"][];
            /** Counts By Status */
            counts_by_status: components["schemas"]["StatusCountRow"][];
            /** Cost Trend Daily */
            cost_trend_daily: components["schemas"]["DailyCostRow"][];
            /** Recent Jobs */
            recent_jobs: components["schemas"]["JobResponse"][];
        };
        /** StatusCountRow */
        StatusCountRow: {
            /** Status */
            status: string;
            /** Count */
            count: number;
        };
        /**
         * UploadResponse
         * @description Returned by POST /uploads/audio. Frontend stashes upload_id and
         *     references it in the stt_pipeline job's extra payload.
         */
        UploadResponse: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Mime */
            mime: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                type?: string | null;
                status?: string | null;
                intern_name?: string | null;
                search?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_output_jobs__job_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subtasks_jobs__job_id__subtasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSubTaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_subtask_output_jobs_subtasks__subtask_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subtask_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subtask_log_jobs_subtasks__subtask_id__log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subtask_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_log_jobs__job_id__log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_confirm_jobs__job_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_stats_summary_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_audio_uploads_audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_audio_uploads_audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
